VantageCloud Lake getting started
Teradata/quickstarts pull request #149
Opened 2024-01-08 14:44 UTC by vidhanbhonsle

2024-01-08 17:51 UTC, adamtwo requested changes

2024-01-08 17:51 UTC, adamtwo commented on modules/ROOT/pages/getting.started.lake.adoc
> += Getting Started with VantageCloud Lake
I think the file name should be `getting-started-with-vantagecloud-lake.adoc` to improve google indexing

2024-01-08 17:51 UTC, adamtwo commented on modules/ROOT/pages/getting.started.lake.adoc
> +Teradata VantageCloud Lake is Teradata's next-generation, cloud-native analytics and data platform. It provides lakehouse deployment patterns along with the ability to run independent elastic workloa
We should say `object storage` instead of `object store`. That's the industry standard way of referring to s3-like buckets.

2024-01-08 17:51 UTC, adamtwo commented on modules/ROOT/pages/getting.started.lake.adoc
> +Go to the URL provided by Teradata, for example, *_ourcompany.innovationlabs.teradata.com_* and Sign on:
no need to capitalize `Sign on`.

2024-01-08 17:51 UTC, adamtwo commented on modules/ROOT/pages/getting.started.lake.adoc
> +In the *SETTINGS*, select the *Internet connection* checkbox and provide the IP addresses(in CIDR format) with which you would want to access your environment.
it would be useful to give an example of a CIDR expression.

2024-01-09 13:17 UTC, Daniel-Itzul approved these changes

2024-01-09 13:17 UTC, Daniel-Itzul commented on modules/ROOT/pages/getting-started-with-vantagecloud-lake.adoc
> +| The DBA account for the database is called "dbc". Set the password for dbc: +
```suggestion
The primary administrative account in a Teradata Vantage environment is known as "dbc". Similar to the root user in Linux, the dbc account holds comprehensive administrative privileges. It is recommended to establish additional administrative users for routine tasks, after the environment is created, and to refrain from sharing or utilizing the dbc credentials.
Set the password for dbc: +
```

2024-01-09 13:19 UTC, Daniel-Itzul approved these changes

2024-01-09 13:21 UTC, merged